### ISSUE TITLE
Same issue SAMLRequest IssueInstant is in the future. ... with tolerance of 0 seconds

### ISSUE THREAD

**Issue by Croquemais** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#8]
Hello,

I have the same issue described on issue 6  (https://github.com/RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration/issues/6).

Exception: SAMLRequest IssueInstant is in the future. System: 11/5/2018 9:59:52 AM with tolerance of 0 seconds. SAML: 

System.Exception: An error was encountered while handling the remote login. ---> System.Exception: SAMLRequest IssueInstant is in the future. System: 11/5/2018 9:59:52 AM with tolerance of 0 seconds. SAML: 11/5/2018 9:59:52 AM

   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Rsk.AspNetCore.Authentication.Saml2p.Saml2pAuthenticationHandler.HandleRequestAsync()
   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

How is it possible to set the "TimeComparisonTolerance" property ?

Thanks a lot.

**Comment by scottbrady91** [comment]
In the latest version of the IdentityServer4 SAML component (`2.2.0-preview3` and above), both IdP and SP can be configured with the following option: `TimeComparisonTolerance`. Setting this will allow you to say how accurate (or not) you want to be with time comparisons. This property is available on `SamlIdpOptions` and `Saml2pAuthenticationOptions`.

Another alternative is to create and register your own implementation of `IDateTimeService` that has the clock skew and accuracy that you need.
