### ISSUE TITLE
Getting error when single signon with HttpRedirect

### ISSUE THREAD

**Issue by Baranitharan84** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#9]
I just upgraded the Rsk.IdentityServer4.Saml version from 2.1.2.18 to 2.3.2.55 and I noticed that when single sign on with HttpRedirect binding we are getting an error in signature validation.
Same action was working  fine though with my previous version of this library.

Something got changed with latest build?

**Request Url:** 
 http://localhost:5000/saml/sso?SAMLRequest=jdFNa8MwDAbge6H%2Fwfje%2BaNJvYokENpLobu0Ww%2B7Oa5HAomdWU7Zz1%2BadbDCGLtKeuCVlKHuWtlDOcTaHez7YDGSj651CF%2BdnA7BgdfYIDjdWYRo4Fg%2B7UE%2BcOiDj974lv40fxONaENsvKNkt81pc1ZK6Iqrc6UUTyprKylX%2BlEszZtcL1WyouRkA44gp6MfFeJgdw6jdnEscbFecLkQybPkkHAQ6pWS7bhG43ScVB1jD4y13ui29hgh5Zyza1SG6CkpvxNtvMOhs%2BFow6Ux9uWw%2FxWLNGXXe93GkJUGaTGfEZJN%2B8OUMBT%2FoBm7E%2FPZrXD%2FkOITAAAAAAAAAAAAAA%3D%3D&RelayState=SJU4voQzFUpSTXcBC2N1u60y4K5GoTBqW6KhYeO_WwiCAvZ-NZ8tmmeJ&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=gDnxSNCusBgmswKiAeaN9yvmMwxTbF3DJATVwqxPD2VcpS%2FRygzeW5KrlEfWCPyVJUFwKJQ8JwcjJiGvko7TDdapHdYS8I6Z6HbJbBbPnLPhLrEdVgsMVeItJOuKVWDHgGUsX1OT%2FeXP83utjhHITCLu3R2sfnK4Rh0LGyNWNcki1e2ZCswKTrO4rhkX7oqsYNAd1K%2FT0DeCIteT%2Fm0QSYDXe2R1rfeuj%2FmUmdeafe9DSvSieRR1qKjyMnBCbp3ViPXmZl%2FCBqCnF8CrbqF98hFlScXvI7iqQbPQx%2B62j3LFUjJHrHZTFumhCvwUKz7R2xiOGAn00YCyKKODgW1f9g%3D%3D

**StackTrace:**

System.NullReferenceException: Object reference not set to an instance of an object.
   at IdentityServer4.Saml.Validation.Validators.SignatureValidator.Validate() in E:\TeamCity\buildAgent\work\73e6199d397b0702\src\IdentityServer4.Saml\Validation\Validators\SignatureValidator.cs:line 78
   at IdentityServer4.Saml.Validation.Saml2SingleSignOnRequestValidator.ValidateAsync(NameValueCollection parameters, String bindingType, String rawUrl, String baseUrl, String issuerUri, ClaimsPrincipal subject) in E:\TeamCity\buildAgent\work\73e6199d397b0702\src\IdentityServer4.Saml\Validation\Saml2SingleSignOnRequestValidator.cs:line 58
   at IdentityServer4.Saml.Endpoints.Saml2SingleSignOnEndpoint.ProcessSingleSignOnRequest(HttpContext context, NameValueCollection parameters, String bindingType, String samlRequestUrl, ClaimsPrincipal user) in E:\TeamCity\buildAgent\work\73e6199d397b0702\src\IdentityServer4.Saml\Endpoints\Saml2SingleSignOnEndpoint.cs:line 139
   at IdentityServer4.Saml.Endpoints.Saml2SingleSignOnEndpoint.ProcessSingleSignOn(HttpContext context) in E:\TeamCity\buildAgent\work\73e6199d397b0702\src\IdentityServer4.Saml\Endpoints\Saml2SingleSignOnEndpoint.cs:line 100
   at IdentityServer4.Saml.Endpoints.Saml2SingleSignOnEndpoint.ProcessAsync(HttpContext context) in E:\TeamCity\buildAgent\work\73e6199d397b0702\src\IdentityServer4.Saml\Endpoints\Saml2SingleSignOnEndpoint.cs:line 59
   at IdentityServer4.Saml.Hosting.IdentityServerSamlMiddleware.Invoke(HttpContext context, ISamlEndpointRouter router, IMemoryCache cache, SamlIdpOptions options) in E:\TeamCity\buildAgent\work\73e6199d397b0702\src\IdentityServer4.Saml\Hosting\IdentityServerSamlMiddleware.cs:line 39
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\Hosting\IdentityServerMiddleware.cs:line 72
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by scottbrady91** [comment]
As we discussed via email, this was due to a different 3rd party library modifying underlying Microsoft code. The fix was to remove usage of the 3rd party library.
